from pathlib import Path
import json
import pandas as pd
import streamlit as st

st.set_page_config(page_title="NIFTY 500 Daily Intelligence", page_icon="📊", layout="wide")

DATA = Path(__file__).parent / "data"

def read_csv_safe(name):
    path = DATA / name
    if not path.exists():
        return pd.DataFrame()
    try:
        return pd.read_csv(path)
    except Exception:
        return pd.DataFrame()

def read_json_safe(name):
    path = DATA / name
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}

report = read_json_safe("nifty500_report.json")
scan = read_csv_safe("nifty500_scan.csv")
audit = read_csv_safe("nifty500_eod_audit.csv")

st.title("📊 NIFTY 500 Daily Intelligence")
st.caption(
    f"Prediction date: {report.get('prediction_date', 'Waiting for first scan')} "
    f"• {report.get('prediction_time', '—')}"
)
st.caption("Daily momentum sets • priority ranking • prediction • EOD verification")

c1, c2, c3, c4 = st.columns(4)
c1.metric("Market Direction", report.get("market_direction", "WAITING"))
c2.metric("Stocks Scanned", report.get("universe_scanned", 0))
c3.metric("Bullish", report.get("bullish", 0))
c4.metric("Bearish", report.get("bearish", 0))

st.header("🏆 Priority Order & Stock Sets")

if scan.empty:
    st.info(
        "The dashboard is working. No NIFTY scan data has been generated yet. "
        "Run the GitHub Action manually once, or wait for the scheduled scan."
    )
else:
    wanted = [
        "priority", "ticker", "set",
        "1Y", "6M", "1M", "1W", "1D",
        "prediction", "confidence", "last_close"
    ]
    columns = [col for col in wanted if col in scan.columns]
    if columns:
        st.dataframe(scan[columns], use_container_width=True, hide_index=True)
    else:
        st.warning("Scan file was found, but it does not contain the expected columns.")

st.header("🎯 EOD Analysis")

required = {"prediction", "actual_eod", "matched"}

if audit.empty:
    st.info("No completed EOD audit yet.")
elif not required.issubset(audit.columns):
    st.info("EOD audit file exists but is not complete yet.")
else:
    audit = audit.copy()
    audit["Result"] = audit["matched"].astype(str).str.lower().map({
        "true": "✅ RIGHT",
        "false": "❌ WRONG"
    }).fillna("—")

    right = int((audit["Result"] == "✅ RIGHT").sum())
    wrong = int((audit["Result"] == "❌ WRONG").sum())
    total = right + wrong

    a1, a2, a3 = st.columns(3)
    a1.metric("Right", right)
    a2.metric("Wrong", wrong)
    a3.metric("Win %", f"{(right / total * 100) if total else 0:.1f}%")

    audit_cols = [
        col for col in [
            "trade_date", "ticker", "priority", "set",
            "prediction", "actual_eod", "eod_move_pct", "Result"
        ]
        if col in audit.columns
    ]

    st.dataframe(
        audit[audit_cols] if audit_cols else audit,
        use_container_width=True,
        hide_index=True,
    )

st.divider()
st.caption(
    "Data is generated by the GitHub workflow. "
    "The dashboard can open safely before the first scan has produced data."
)
